---
    - name: Display - task-01 
      ansible.builtin.debug:
          msg: "This is my 1st message - display - task-01 - import"
    - name: Display - task-02 
      ansible.builtin.debug:
          msg: "This is my 2nd message - display - task-02 - import"


  
