---
- name: Handlers example
  hosts: dev
  force_handlers: True
  tasks:
     - name: Execute command 
       ansible.builtin.shell: date
       #changed_when: false 
       notify: 
            - display msg 
     - name: Task-02 
       ansible.builtin.debug:
          msg: "This is task-2"
       failed_when: true 

     - name: Task-03 
       ansible.builtin.debug:
          msg: "This is task-3"

  handlers:  
     - name: display msg
       ansible.builtin.debug:
          msg: "This is task4 - From handlers"
 
