---
 - name: Jinja2 deployment 
   hosts: all 
   tasks:
      - name: Template a file to /etc/file.conf
        ansible.builtin.template:
           src: hosts.j2
           dest: /tmp/demo-1-hosts
        #when: inventory_hostname in groups['dev']
      - name: Template - genereate hw report
        ansible.builtin.template:
           #src: hosts-example-02.j2
           src: hosts-example-02-syntax.j2
           dest: /tmp/report
        when: inventory_hostname in groups['dev']
