---
- name: Register variable 
  hosts: dev
  tasks:
     - name: Print the gateway for each host when defined
       ansible.builtin.debug:
             msg: "{{ inventory_hostname }},{{ ansible_default_ipv4.gateway }},{{ ansible_default_ipv4.macaddress}},{{ansible_architecture}}"


     - name: Print the gateway for each host when defined
       ansible.builtin.copy:
            content: "{{ inventory_hostname }},{{ ansible_default_ipv4.gateway }},{{ ansible_default_ipv4.macaddress}},{{ansible_architecture}}"
            dest: /tmp/system_detail.csv
