---
- name: Restart multiple services.
  hosts: web 
  vars_files:
    - svc_list.yml
  tasks:
    - name: Restart multiple service.
      ansible.builtin.service:
          name: "{{ item }}"
          state: restarted 
      loop: "{{ service_list }}"

