---
- name: Restart multiple services.
  hosts: web 
  vars:
     service_list: 
          - sshd 
          - httpd
          - rsyslog 
          - crond 
  tasks:
    - name: Restart multiple service.
      ansible.builtin.service:
          name: "{{ item }}"
          state: restarted 
      loop: "{{ service_list }}"

