---
 - name: Apache deployment - 1st play in this playbook
   hosts: web 
   tasks:
     - name: Apache package installation - 1st Task 
       ansible.builtin.yum: 
         name: httpd
         state: present

     - name: Firewalld package installation - 2nd Task 
       ansible.builtin.yum: 
         name: firewalld
         state: present

     - name: Start and enable Apache service - 3rd Task
       ansible.builtin.service:
         name: httpd
         state: started
         enabled: true 

     - name: Start and enable Firewalld service - 4th Task
       ansible.builtin.service:
         name: firewalld
         state: started
         enabled: true 

     - name: Deploying index.html page. - 5th Task 
       ansible.builtin.copy:
         content: "##************** This is my web server !!************** \n"
         dest: /var/www/html/index.html 

     - name: ENnable firewalld rule - http - 6th Task 
       ansible.posix.firewalld:
         service: http
         immediate: yes
         permanent: yes
         state: enabled
...
