---
# tasks file for apache
- name: Install apache packages.
  ansible.builtin.dnf:
       name: "{{ apache_package }}"
       state: present 

- name: Start and enable service.
  ansible.builtin.service:
       name: "{{ apache_service }}"
       state: started 
       enabled: yes 

- name: Deploy application - index.html 
  ansible.builtin.copy:
       content: "This is my web server \n"
       dest: /var/www/html/index.html 
  notify:
      - dummy_restart_svc 
...
